# Generated by Django 4.2.9 on 2024-04-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('clientID', models.IntegerField()),
                ('account_number', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('account_role', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('abn', models.CharField(max_length=255)),
                ('added_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('clientID', models.BigAutoField(primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('added_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('contract_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('added_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.account')),
            ],
        ),
    ]
