# Generated by Django 4.2.9 on 2024-04-30 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0005_alter_clientcontract_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('deal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deal_name', models.CharField(max_length=128)),
                ('pricing', models.FloatField()),
                ('duration', models.CharField(max_length=128)),
                ('sla', models.CharField(max_length=128)),
                ('deal_status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.account')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealContract',
            fields=[
                ('contract_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.deals')),
            ],
        ),
    ]
