# Generated by Django 4.2.9 on 2024-05-02 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0007_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcontract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=128)),
                ('employee_phone', models.CharField(max_length=128)),
                ('employee_email', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.department')),
            ],
        ),
    ]
