# Generated by Django 4.2.9 on 2024-05-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0009_employee_employee_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_pic',
            field=models.ImageField(blank=True, null=True, upload_to='employee/'),
        ),
    ]
