# Generated by Django 4.2.9 on 2024-05-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0010_alter_employee_employee_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.employee')),
            ],
            options={
                'unique_together': {('department', 'employee', 'date')},
            },
        ),
    ]
