# Generated by Django 4.2.9 on 2024-05-08 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0014_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='industries',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.CreateModel(
            name='SupplierAgent',
            fields=[
                ('agent_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=128)),
                ('regions', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.supplier')),
            ],
        ),
    ]
