# Generated by Django 4.2.9 on 2024-05-09 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0017_suppliertrades_delete_suppliertraders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliertrades',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.supplieragent'),
        ),
    ]
