# Generated by Django 4.2.9 on 2024-05-09 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0018_alter_suppliertrades_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorSkill',
            fields=[
                ('contractor_skill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rates', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('license_name', models.CharField(max_length=128)),
                ('license_status', models.BooleanField(default=1)),
                ('accreditation', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.supplierskill')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.suppliertrades')),
            ],
        ),
    ]
