# Generated by Django 4.2.9 on 2024-05-17 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0020_rename_contractorskill_suppliercontractorskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSupplier',
            fields=[
                ('material_supplier_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=128)),
                ('business_name', models.CharField(max_length=128)),
                ('business_address', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('material_support_category', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
