# Generated by Django 4.2.9 on 2024-05-20 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0021_materialsupplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoresBranch',
            fields=[
                ('store_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('abn', models.CharField(max_length=50, unique=True)),
                ('branch_name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('region_of_operation', models.CharField(max_length=128)),
                ('branch_contact', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material_supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.materialsupplier')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInvoice',
            fields=[
                ('material_invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=128)),
                ('quantity', models.FloatField()),
                ('individual_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('approver', models.CharField(max_length=128)),
                ('date_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.materialsupplier')),
            ],
        ),
    ]
