# Generated by Django 4.2.9 on 2024-05-20 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0022_storesbranch_materialinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialinvoice',
            name='individual_price',
        ),
        migrations.RemoveField(
            model_name='materialinvoice',
            name='items',
        ),
        migrations.RemoveField(
            model_name='materialinvoice',
            name='quantity',
        ),
        migrations.CreateModel(
            name='MaterialInvoiceItems',
            fields=[
                ('material_invoice_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('items', models.CharField(max_length=128)),
                ('quantity', models.FloatField()),
                ('individual_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.materialinvoice')),
            ],
        ),
    ]
