# Generated by Django 4.2.9 on 2024-05-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0023_remove_materialinvoice_individual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinvoice',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
