# Generated by Django 4.2.9 on 2024-06-03 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0025_alter_materialinvoice_store_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinvoiceitems',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('work_order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplier_list_id', models.CharField(max_length=128)),
                ('work_order_type', models.CharField(max_length=128)),
                ('work_order_status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.dealcontract')),
            ],
        ),
    ]
