# Generated by Django 4.2.9 on 2024-06-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0026_alter_materialinvoiceitems_quantity_workorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealcontract',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
