# Generated by Django 4.2.9 on 2024-06-03 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0027_dealcontract_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrders',
            fields=[
                ('job_order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_desc', models.CharField(max_length=128)),
                ('job_type', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.employee')),
                ('work_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.workorders')),
            ],
        ),
    ]
