# Generated by Django 4.2.9 on 2024-06-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0028_joborders'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborders',
            name='job_status',
            field=models.BooleanField(default=1),
        ),
    ]
