# Generated by Django 4.2.9 on 2024-06-03 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0029_joborders_job_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderInvoice',
            fields=[
                ('work_order_invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approval_status', models.CharField(choices=[('APPROVED', 'Approved'), ('DECLINED', 'Declined')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.workorders')),
            ],
        ),
    ]
