# Generated by Django 4.2.9 on 2024-06-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0031_joborderinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborderinvoice',
            name='abn',
            field=models.CharField(max_length=20),
        ),
    ]
