# Generated by Django 4.2.9 on 2024-06-03 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0032_alter_joborderinvoice_abn'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOrderTimesheet',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.workorderinvoice')),
            ],
        ),
    ]
