# Generated by Django 4.2.9 on 2024-06-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0033_jobordertimesheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobordertimesheet',
            name='job_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.joborders'),
        ),
    ]
