# Generated by Django 4.2.9 on 2024-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0034_alter_jobordertimesheet_job_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobordertimesheet',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('DECLINED', 'Declined')], max_length=32, null=True),
        ),
    ]
