# Generated by Django 4.2.9 on 2024-06-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0037_alter_jobordertimesheet_word_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobordertimesheet',
            name='work_order_id',
        ),
    ]
