# Generated by Django 4.2.9 on 2024-06-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0039_alter_jobordertimesheet_work_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobordertimesheet',
            old_name='work_order_id',
            new_name='work_order_id',
        ),
    ]
