# Generated by Django 4.2.9 on 2024-06-03 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appAdmin', '0040_rename_work_order_id_jobordertimesheet_word_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_order_invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.joborderinvoice')),
                ('work_order_invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAdmin.workorderinvoice')),
            ],
        ),
    ]
