# Generated by Django 4.2.9 on 2024-06-03 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAdmin', '0041_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='job_order_amount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='job_order_invoice_id',
        ),
        migrations.AddField(
            model_name='billing',
            name='material_invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='material_invoice_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAdmin.materialinvoice'),
        ),
    ]
